FROM node:18-bullseye

RUN apt -qq update && apt -qq upgrade -y && apt -qq clean && rm -rf /var/lib/apt/lists/*

ARG version=4.7.1
ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

ENV HOST=0.0.0.0
ENV PORT=1337

RUN yarn global add create-strapi-app@${version}
RUN create-strapi-app strapi --quickstart --no-run
RUN rm /strapi/.env

WORKDIR /strapi
VOLUME /strapi/public/uploads
EXPOSE ${PORT}

HEALTHCHECK --start-period=30s --timeout=3s \
    CMD curl -X HEAD http://localhost:${PORT}/_health -s || exit 1

CMD ["/usr/local/bin/yarn", "start"]
